
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: registry.opensuse.org/yast/sle-15/sp5/containers/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Unit Tests
      run: rake test:unit
      # enable code coverage reporting
      env:
        COVERAGE: 1

    # send the coverage report to coveralls.io
    - name: Coveralls Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  # FIXME: Rubocop is not configured here, uncomment this part after enabling it:
  # Rubocop:
  #   runs-on: ubuntu-latest
  #   container: registry.opensuse.org/yast/sle-15/sp5/containers/yast-ruby:latest

  #   steps:

  #   - name: Git Checkout
  #     uses: actions/checkout@v2

  #   - name: Rubocop
  #     run: rake check:rubocop

  Package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: registry.opensuse.org/yast/sle-15/sp5/containers/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Build Workaround
      run: |
        # a workaround to allow package building on a non-s390 machine
        sed -i "/^ExclusiveArch:/d" package/*.spec

    - name: Package Build
      run: yast-ci-ruby -o package
      env:
        # ignore the spec file modification done above
        CHECK_MODIFIED: 0

  Yardoc:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: registry.opensuse.org/yast/sle-15/sp5/containers/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Yardoc
      run: rake check:doc

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: registry.opensuse.org/yast/sle-15/sp5/containers/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Perl Syntax
      run: yast-ci-ruby -o perl_syntax

    - name: POT Check
      run: rake check:pot
